#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the WxTx_user.mk file instead.
#

# Constants automatically defined by the selected modules
WxTx_DEBUG = 1

# Our target application
TRG += WxTx

WxTx_PREFIX = "/usr/bin/avr-"

WxTx_SUFFIX = ""

WxTx_SRC_PATH = WxTx

WxTx_HW_PATH = WxTx

# Files automatically generated by the wizard. DO NOT EDIT, USE WxTx_USER_CSRC INSTEAD!
WxTx_WIZARD_CSRC = \
	bertos/algo/crc8.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/i2c_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ow_1wire.c \
	bertos/drv/ow_ds18x20.c \
	bertos/drv/ow_ds2438.c \
	bertos/drv/i2c.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/drv/bme280.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxTx_USER_PCSRC INSTEAD!
WxTx_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxTx_USER_CPPASRC INSTEAD!
WxTx_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxTx_USER_CXXSRC INSTEAD!
WxTx_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxTx_USER_ASRC INSTEAD!
WxTx_WIZARD_ASRC = \
	 \
	#

WxTx_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(WxTx_HW_PATH) -I$(WxTx_SRC_PATH) $(WxTx_CPU_CPPFLAGS) $(WxTx_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_LDFLAGS = $(WxTx_CPU_LDFLAGS) $(WxTx_WIZARD_LDFLAGS) $(WxTx_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_CPPAFLAGS = $(WxTx_CPU_CPPAFLAGS) $(WxTx_WIZARD_CPPAFLAGS) $(WxTx_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_CSRC = $(WxTx_CPU_CSRC) $(WxTx_WIZARD_CSRC) $(WxTx_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_PCSRC = $(WxTx_CPU_PCSRC) $(WxTx_WIZARD_PCSRC) $(WxTx_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_CPPASRC = $(WxTx_CPU_CPPASRC) $(WxTx_WIZARD_CPPASRC) $(WxTx_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_CXXSRC = $(WxTx_CPU_CXXSRC) $(WxTx_WIZARD_CXXSRC) $(WxTx_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_ASRC = $(WxTx_CPU_ASRC) $(WxTx_WIZARD_ASRC) $(WxTx_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxTx_MCU = atmega328p
WxTx_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
WxTx_PROGRAMMER_CPU = atmega328p
WxTx_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
WxTx_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
WxTx_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
WxTx_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(WxTx_SRC_PATH)/WxTx_user.mk
