#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the WxRx_user.mk file instead.
#

# Constants automatically defined by the selected modules
WxRx_DEBUG = 1

# Our target application
TRG += WxRx

WxRx_PREFIX = "avr-"

WxRx_SUFFIX = ""

WxRx_SRC_PATH = boards/arduino/examples/arduino_WxRx

WxRx_HW_PATH = boards/arduino

# Files automatically generated by the wizard. DO NOT EDIT, USE WxRx_USER_CSRC INSTEAD!
WxRx_WIZARD_CSRC = \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/struct/heap.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxRx_USER_PCSRC INSTEAD!
WxRx_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxRx_USER_CPPASRC INSTEAD!
WxRx_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxRx_USER_CXXSRC INSTEAD!
WxRx_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE WxRx_USER_ASRC INSTEAD!
WxRx_WIZARD_ASRC = \
	 \
	#

WxRx_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(WxRx_HW_PATH) -I$(WxRx_SRC_PATH) $(WxRx_CPU_CPPFLAGS) $(WxRx_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_LDFLAGS = $(WxRx_CPU_LDFLAGS) $(WxRx_WIZARD_LDFLAGS) $(WxRx_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_CPPAFLAGS = $(WxRx_CPU_CPPAFLAGS) $(WxRx_WIZARD_CPPAFLAGS) $(WxRx_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_CSRC = $(WxRx_CPU_CSRC) $(WxRx_WIZARD_CSRC) $(WxRx_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_PCSRC = $(WxRx_CPU_PCSRC) $(WxRx_WIZARD_PCSRC) $(WxRx_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_CPPASRC = $(WxRx_CPU_CPPASRC) $(WxRx_WIZARD_CPPASRC) $(WxRx_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_CXXSRC = $(WxRx_CPU_CXXSRC) $(WxRx_WIZARD_CXXSRC) $(WxRx_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_ASRC = $(WxRx_CPU_ASRC) $(WxRx_WIZARD_ASRC) $(WxRx_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
WxRx_MCU = atmega328p
WxRx_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
WxRx_PROGRAMMER_CPU = atmega328p
WxRx_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
WxRx_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
WxRx_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
WxRx_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(WxRx_SRC_PATH)/WxRx_user.mk
