#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the arduino_kiss_g4xyw_user.mk file instead.
#

# Constants automatically defined by the selected modules
arduino_kiss_g4xyw_DEBUG = 1

# Our target application
TRG += arduino_kiss_g4xyw

arduino_kiss_g4xyw_PREFIX = "avr-"

arduino_kiss_g4xyw_SUFFIX = ""

arduino_kiss_g4xyw_SRC_PATH = boards/arduino/examples/arduino_kiss_g4xyw

arduino_kiss_g4xyw_HW_PATH = boards/arduino

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kiss_g4xyw_USER_CSRC INSTEAD!
arduino_kiss_g4xyw_WIZARD_CSRC = \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/net/hdlc.c \
	bertos/net/kiss.c \
	bertos/net/xywmodem.c \
	bertos/struct/kfile_mem.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kiss_g4xyw_USER_PCSRC INSTEAD!
arduino_kiss_g4xyw_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kiss_g4xyw_USER_CPPASRC INSTEAD!
arduino_kiss_g4xyw_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kiss_g4xyw_USER_CXXSRC INSTEAD!
arduino_kiss_g4xyw_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE arduino_kiss_g4xyw_USER_ASRC INSTEAD!
arduino_kiss_g4xyw_WIZARD_ASRC = \
	 \
	#

arduino_kiss_g4xyw_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(arduino_kiss_g4xyw_HW_PATH) -I$(arduino_kiss_g4xyw_SRC_PATH) $(arduino_kiss_g4xyw_CPU_CPPFLAGS) $(arduino_kiss_g4xyw_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_LDFLAGS = $(arduino_kiss_g4xyw_CPU_LDFLAGS) $(arduino_kiss_g4xyw_WIZARD_LDFLAGS) $(arduino_kiss_g4xyw_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_CPPAFLAGS = $(arduino_kiss_g4xyw_CPU_CPPAFLAGS) $(arduino_kiss_g4xyw_WIZARD_CPPAFLAGS) $(arduino_kiss_g4xyw_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_CSRC = $(arduino_kiss_g4xyw_CPU_CSRC) $(arduino_kiss_g4xyw_WIZARD_CSRC) $(arduino_kiss_g4xyw_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_PCSRC = $(arduino_kiss_g4xyw_CPU_PCSRC) $(arduino_kiss_g4xyw_WIZARD_PCSRC) $(arduino_kiss_g4xyw_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_CPPASRC = $(arduino_kiss_g4xyw_CPU_CPPASRC) $(arduino_kiss_g4xyw_WIZARD_CPPASRC) $(arduino_kiss_g4xyw_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_CXXSRC = $(arduino_kiss_g4xyw_CPU_CXXSRC) $(arduino_kiss_g4xyw_WIZARD_CXXSRC) $(arduino_kiss_g4xyw_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_ASRC = $(arduino_kiss_g4xyw_CPU_ASRC) $(arduino_kiss_g4xyw_WIZARD_ASRC) $(arduino_kiss_g4xyw_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
arduino_kiss_g4xyw_MCU = atmega328p
arduino_kiss_g4xyw_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
arduino_kiss_g4xyw_PROGRAMMER_CPU = atmega328p
arduino_kiss_g4xyw_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
arduino_kiss_g4xyw_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
arduino_kiss_g4xyw_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
arduino_kiss_g4xyw_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(arduino_kiss_g4xyw_SRC_PATH)/arduino_kiss_g4xyw_user.mk
